# Generated by Django 3.2.10 on 2022-01-01 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Coments',
        ),
    ]
