# Generated by Django 3.2.10 on 2022-01-01 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_coment_coments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='published_date',
        ),
        migrations.AddField(
            model_name='coments',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
