# Generated by Django 3.2.10 on 2022-01-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220101_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coments',
        ),
    ]
