# Generated by Django 3.2.10 on 2022-01-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_coments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
