# Generated by Django 3.2.10 on 2022-01-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_post_id_comments_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
