# Generated by Django 3.2.10 on 2022-01-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
